# Generated by Django 5.0.1 on 2024-09-05 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 18, 7, 36, 154520)),
        ),
    ]
