# Generated by Django 5.0.1 on 2024-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
