# Generated by Django 5.0.1 on 2024-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_otp_customuser_otp_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
