# Generated by Django 5.0.1 on 2024-09-19 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_at', models.CharField(blank=True, max_length=255, null=True)),
                ('works_from', models.CharField(blank=True, max_length=255, null=True)),
                ('works_to', models.CharField(blank=True, max_length=255, null=True)),
                ('studied_at', models.CharField(blank=True, max_length=255, null=True)),
                ('lives_in', models.CharField(blank=True, max_length=255, null=True)),
                ('lives_at', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
