# Generated by Django 5.0.1 on 2024-09-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('attend_from', models.CharField(max_length=255)),
                ('attend_to', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='works_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_at', models.CharField(max_length=255)),
                ('works_from', models.CharField(max_length=255)),
                ('works_to', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=0)),
                ('current', models.BooleanField(default=0)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
