# Generated by Django 5.0.1 on 2024-09-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_college_works_place_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works_place',
            old_name='works_at',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='works_place',
            name='private',
        ),
        migrations.AddField(
            model_name='works_place',
            name='audience',
            field=models.IntegerField(default=0),
        ),
    ]
