# Generated by Django 5.0.1 on 2024-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_works_at_works_place_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_place',
            name='works_from',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='works_place',
            name='works_to',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
