# Generated by Django 5.0.1 on 2024-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_works_place_works_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_place',
            name='works_from',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='works_place',
            name='works_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
