# Generated by Django 5.0.1 on 2024-09-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_works_place_works_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='address',
        ),
        migrations.RemoveField(
            model_name='college',
            name='type',
        ),
    ]
