# Generated by Django 5.0.1 on 2024-09-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_college_address_remove_college_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='audience',
            field=models.IntegerField(default=0),
        ),
    ]
