# Generated by Django 5.0.1 on 2024-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_college_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
