# Generated by Django 5.0.1 on 2024-09-21 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_college_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='attend_from',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='attend_to',
            field=models.DateField(max_length=255),
        ),
        migrations.CreateModel(
            name='places_lived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('moved', models.CharField(blank=True, max_length=255, null=True)),
                ('audience', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
