# Generated by Django 5.0.1 on 2024-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_college_attend_from_alter_college_attend_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='relationship',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('in a relationship', 'In a relationship'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('seprated', 'Seprated')], max_length=255, null=True),
        ),
    ]
