# Generated by Django 5.0.1 on 2024-09-21 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='relationship',
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('date_of_birth_audience', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('gender_audience', models.IntegerField()),
                ('primary_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('primary_phone_number_audience', models.IntegerField()),
                ('secondary_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_phone_number_audience', models.IntegerField()),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('relationship', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('in a relationship', 'In a relationship'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('seprated', 'Seprated')], max_length=255, null=True)),
                ('relationship_audience', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
