# Generated by Django 5.0.1 on 2024-10-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_bio_notification_friend_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
